name: 'Deploy dev app'
on:
  workflow_call:
    secrets: inherit

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '>16.14'
      - name: 'Switch to toolkit-react package directory'
        run: cd packages/toolkit-react
      - name: 'Install Vercel CLI'
        run: npm install --global vercel@latest
      - name: 'Pull Vercel environment'
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: 'Build Storybook static app'
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: 'Deploy Storybook static app to Vercel'
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}