name: 'Run tests'
on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Install Node'
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: 'Install dependencies'
        run: npm install -ws=false && npm install -w package
      - name: 'Run unit tests'
        run: npm run coverage -w package
      - name: 'Report coverage'
        if: ${{ always() }} # Generate report if tests are failing, too
        uses: davelosert/vitest-coverage-report-action@v1
        with:
          working-directory: 'package'