name: 'Run tests'
on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Install Node'
        uses: actions/setup-node@v2
        with:
          node-version: '>16.14'
      - name: 'Install dependencies'
        working-directory: packages/toolkit-react
        run: npm ci
      - name: 'Run unit tests'
        working-directory: packages/toolkit-react
        run: npm run coverage
      - name: 'Report coverage'
        working-directory: packages/toolkit-react
        if: ${{ always() }} # Generate report if tests are failing, too
        uses: davelosert/vitest-coverage-report-action@v1